// Running exercise database
export const exerciseDatabase = {
  // Running workouts
  "Interval Run": {
    category: "Speed Work",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Running Shoes",
    difficulty: "Intermediate",
    description: "Alternating between fast and recovery efforts to build speed and VO2max.",
    steps: [
      "Warm up with 10 minutes of easy jogging",
      "Run hard for the prescribed interval (e.g. 400m, 800m)",
      "Jog or walk for the recovery period",
      "Repeat for the prescribed number of reps",
      "Cool down with 10 minutes of easy jogging",
    ],
    tips: [
      "Run the first interval slightly slower than your target",
      "Focus on consistent pacing across all intervals",
      "Recovery should be active (jogging), not standing still",
      "Stay relaxed in your upper body during hard efforts",
      "If pace drops significantly, end the workout early",
    ],
    commonMistakes: [
      "Going out too fast on the first rep",
      "Not warming up sufficiently",
      "Standing still during recovery instead of jogging",
    ],
    image: "/exercises/interval-run.jpg",
  },
  "Tempo Run": {
    category: "Threshold",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Running Shoes",
    difficulty: "Intermediate",
    description: "A sustained effort run at 'comfortably hard' pace to improve lactate threshold.",
    steps: [
      "Warm up with 10 minutes of easy jogging",
      "Increase pace to comfortably hard — short phrases only",
      "Maintain this pace for the prescribed duration",
      "Focus on staying relaxed despite the effort",
      "Cool down with 10 minutes of easy jogging",
    ],
    tips: [
      "Tempo pace is about 85-90% of max effort",
      "You should be able to say a few words but not hold a conversation",
      "Start conservatively — you can always speed up",
      "Focus on maintaining even effort, not pace",
      "Stay relaxed in your upper body",
    ],
    commonMistakes: [
      "Starting too fast and fading",
      "Running at race pace instead of tempo",
      "Skipping the warm-up",
    ],
    image: "/exercises/tempo-run.jpg",
  },
  "Long Run": {
    category: "Endurance",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Running Shoes",
    difficulty: "Intermediate",
    description: "Extended easy running to build aerobic base and mental toughness.",
    steps: [
      "Start with a 5-minute warm-up walk",
      "Run at an easy, conversational pace",
      "Focus on time on feet rather than speed",
      "Stay hydrated if running over 60 minutes",
      "Cool down with walking and stretching",
    ],
    tips: [
      "Start slower than you think you need to",
      "Bring water or plan routes with water stops for longer runs",
      "Consider nutrition for runs over 90 minutes",
      "Run by time/effort, not pace",
      "Build duration gradually (10% per week max)",
    ],
    commonMistakes: [
      "Starting too fast",
      "Not bringing hydration on hot days",
      "Increasing distance too quickly",
    ],
    image: "/exercises/long-run.jpg",
  },
  "Easy Run": {
    category: "Base",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Running Shoes",
    difficulty: "Beginner",
    description: "A low-intensity run that builds aerobic base and aids recovery.",
    steps: [
      "Start with a 5-minute warm-up walk or very slow jog",
      "Run at a conversational pace (you should be able to talk)",
      "Focus on relaxed breathing and smooth form",
      "Maintain consistent effort, not speed",
      "Cool down with walking at the end",
    ],
    tips: [
      "If you can't talk, you're going too fast",
      "Keep your cadence high (170-180 steps per minute)",
      "Relax your shoulders and hands",
      "Land with your foot under your body",
      "Most of your running should be at this easy pace",
    ],
    commonMistakes: [
      "Running too fast (most common mistake!)",
      "Starting too fast and slowing down",
      "Tensing up shoulders and hands",
    ],
    image: "/exercises/easy-run.jpg",
  },
  "Hill Repeats": {
    category: "Speed Work",
    muscles: ["Legs", "Glutes", "Cardiovascular System"],
    equipment: "Running Shoes, Hill",
    difficulty: "Intermediate",
    description: "Repeated uphill efforts that build power, speed, and running economy.",
    steps: [
      "Warm up with 10-15 minutes of easy jogging on flat ground",
      "Find a hill with moderate incline (4-8% grade)",
      "Run hard uphill for the prescribed duration",
      "Jog or walk back down for recovery",
      "Repeat for the prescribed number of reps",
    ],
    tips: [
      "Shorten your stride and drive your knees up on the hill",
      "Pump your arms to generate power",
      "Lean slightly forward from the ankles, not the waist",
      "Use the downhill jog as full recovery",
      "Start with fewer reps and build over weeks",
    ],
    commonMistakes: [
      "Choosing a hill that's too steep",
      "Not recovering fully between reps",
      "Overstriding on the uphill",
    ],
    image: "/exercises/hill-repeats.jpg",
  },
  "Fartlek": {
    category: "Speed Work",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Running Shoes",
    difficulty: "Beginner",
    description: "Unstructured speed play — alternating between fast and easy running by feel.",
    steps: [
      "Start with 10 minutes of easy jogging",
      "Pick a landmark (tree, light post) and run fast to it",
      "Recover with easy jogging until you feel ready",
      "Repeat with varying distances and efforts",
      "Cool down with 10 minutes of easy jogging",
    ],
    tips: [
      "There are no set rules — run by feel and have fun",
      "Vary the length of your fast efforts",
      "Don't stress about pace — focus on effort changes",
      "Great way to introduce speed work for beginners",
      "Use landmarks or music as cues to change pace",
    ],
    commonMistakes: [
      "Making every surge all-out (vary the effort)",
      "Not including enough easy running between surges",
      "Overthinking it — fartlek should be playful",
    ],
    image: "/exercises/fartlek.jpg",
  },
  "Progression Run": {
    category: "Threshold",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Running Shoes",
    difficulty: "Intermediate",
    description: "A run that starts easy and gradually gets faster, teaching pace discipline.",
    steps: [
      "Start at a very easy, comfortable pace",
      "Every mile or every few minutes, increase pace slightly",
      "Finish the last portion at tempo or faster",
      "The effort should feel controlled throughout",
      "Cool down with walking",
    ],
    tips: [
      "Start truly easy — the first miles should feel almost too slow",
      "Each increase should be subtle, not a big jump",
      "Finish feeling strong, not destroyed",
      "Great for learning negative split pacing",
      "Focus on finishing fast, not starting fast",
    ],
    commonMistakes: [
      "Starting too fast (defeats the purpose)",
      "Making the jumps in pace too large",
      "Trying to run the last portion at sprint pace",
    ],
    image: "/exercises/progression-run.jpg",
  },
  "Strides": {
    category: "Speed Work",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Running Shoes",
    difficulty: "Beginner",
    description: "Short accelerations that improve running form and neuromuscular coordination.",
    steps: [
      "Find a flat, smooth surface (100m)",
      "Gradually accelerate to about 90% effort over 20-30m",
      "Hold that fast pace for 30-40m",
      "Gradually decelerate over the final 20-30m",
      "Walk back to start and repeat 4-6 times",
    ],
    tips: [
      "Focus on smooth, relaxed speed — not sprinting",
      "Keep your form tall and light",
      "Full recovery between reps (walk back)",
      "Great to add after easy runs 2-3 times per week",
      "Think 'fast and relaxed' not 'hard and tense'",
    ],
    commonMistakes: [
      "Going all-out instead of controlled acceleration",
      "Tensing up at top speed",
      "Not recovering fully between reps",
    ],
    image: "/exercises/strides.jpg",
  },
  "Dynamic Stretching": {
    category: "Mobility",
    muscles: ["Full Body"],
    equipment: "None",
    difficulty: "Beginner",
    description: "Active stretching movements to prepare your body for running.",
    steps: [
      "Perform leg swings (forward/back, side to side) — 10 each leg",
      "Walking lunges with a twist — 10 each side",
      "High knees for 30 seconds",
      "Butt kicks for 30 seconds",
      "Hip circles — 10 each direction",
    ],
    tips: [
      "Do these before runs, not static stretching",
      "Keep movements controlled but not slow",
      "Focus on the muscles you'll use most (hips, quads, calves)",
      "Increase range of motion gradually",
      "5-10 minutes is enough",
    ],
    commonMistakes: [
      "Skipping warm-up entirely",
      "Doing static stretching before a run (save for after)",
      "Rushing through the movements",
    ],
    image: "/exercises/dynamic-stretching.jpg",
  },
  "Foam Rolling": {
    category: "Recovery",
    muscles: ["Full Body"],
    equipment: "Foam Roller",
    difficulty: "Beginner",
    description: "Self-myofascial release to reduce muscle tension and aid recovery.",
    steps: [
      "Roll IT band slowly from hip to knee — 60 seconds each side",
      "Roll quads front and sides — 60 seconds each leg",
      "Roll calves — 60 seconds each leg",
      "Roll glutes — sit on roller and cross ankle over knee",
      "Roll upper back — arms crossed, roll mid to upper back",
    ],
    tips: [
      "Roll slowly — 1 inch per second",
      "Pause on tender spots for 20-30 seconds",
      "Breathe deeply and try to relax into it",
      "Don't roll directly on bones or joints",
      "10-15 minutes post-run is ideal",
    ],
    commonMistakes: [
      "Rolling too fast",
      "Skipping tender spots (those need the most attention)",
      "Rolling directly on the IT band bone",
    ],
    image: "/exercises/foam-rolling.jpg",
  },
  "Recovery Run": {
    category: "Recovery",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Running Shoes",
    difficulty: "Beginner",
    description: "A very short, very easy run to promote blood flow and recovery.",
    steps: [
      "Start with a 5-minute walk",
      "Run at the easiest possible pace — slower than your easy run",
      "Keep it short: 15-25 minutes total",
      "If anything hurts, walk instead",
      "End with 5 minutes of walking and gentle stretching",
    ],
    tips: [
      "This should feel ridiculously easy",
      "If you're sore from yesterday's workout, this should help",
      "Pace doesn't matter — effort should be minimal",
      "Walking is perfectly fine if running feels too hard",
      "Keep it short — this is about recovery, not fitness",
    ],
    commonMistakes: [
      "Running too fast (this is the #1 mistake)",
      "Running too long",
      "Doing a recovery run when you need a rest day",
    ],
    image: "/exercises/recovery-run.jpg",
  },
  "Yoga for Runners": {
    category: "Cross Training",
    muscles: ["Full Body", "Core", "Flexibility"],
    equipment: "Yoga Mat",
    difficulty: "Beginner",
    description: "Yoga sequence targeting common tight spots for runners.",
    steps: [
      "Start with downward dog — hold for 5 breaths",
      "Low lunge with hip opener — hold 60 sec each side",
      "Pigeon pose — hold 60 sec each side",
      "Reclined hamstring stretch — hold 60 sec each side",
      "Supine twist — hold 60 sec each side",
    ],
    tips: [
      "Focus on hip openers and hamstring flexibility",
      "Breathe deeply and don't force any stretch",
      "Hold each pose long enough to feel a release",
      "Great for recovery days or after long runs",
      "20-30 minutes is plenty",
    ],
    commonMistakes: [
      "Pushing too hard into stretches",
      "Holding breath instead of breathing deeply",
      "Skipping hip-opening poses",
    ],
    image: "/exercises/yoga-runners.jpg",
  },
  "Cycling (Cross Training)": {
    category: "Cross Training",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Bike or Stationary Bike",
    difficulty: "Beginner",
    description: "Low-impact aerobic cross-training that builds fitness without running impact.",
    steps: [
      "Set up with proper seat height (slight bend in knee at bottom)",
      "Warm up with 5 minutes of easy spinning",
      "Maintain moderate effort for prescribed duration",
      "Keep cadence at 80-90 RPM for best crossover to running",
      "Cool down with 5 minutes of easy spinning",
    ],
    tips: [
      "Keep effort easy to moderate — this is supplemental",
      "Higher cadence is better for running crossover",
      "Great substitute when recovering from a running injury",
      "30-45 minutes is a good session length",
      "Don't make it a hard workout — save intensity for running",
    ],
    commonMistakes: [
      "Grinding in too hard a gear (spin lighter!)",
      "Making it an intense workout when it should be easy",
      "Poor bike fit causing knee pain",
    ],
    image: "/exercises/cycling.jpg",
  },
  "Swimming (Cross Training)": {
    category: "Cross Training",
    muscles: ["Full Body", "Cardiovascular System"],
    equipment: "Pool, Goggles",
    difficulty: "Beginner",
    description: "Full-body, zero-impact cross-training that builds aerobic fitness.",
    steps: [
      "Warm up with 200m easy freestyle",
      "Swim at a comfortable pace for prescribed duration",
      "Mix in different strokes if you're comfortable",
      "Focus on breathing rhythm and relaxation",
      "Cool down with 100m easy backstroke",
    ],
    tips: [
      "Don't worry about speed — focus on smooth strokes",
      "Breathe every 3 strokes for bilateral breathing",
      "Use a pull buoy if your legs are tired from running",
      "20-30 minutes is a great recovery swim",
      "Swimming is excellent for active recovery days",
    ],
    commonMistakes: [
      "Holding breath instead of rhythmic breathing",
      "Kicking too hard (save your legs for running)",
      "Going too hard — keep it easy and enjoyable",
    ],
    image: "/exercises/swimming.jpg",
  },
};

// Get exercise by name (handles partial matches)
export function getExercise(name) {
  // Try exact match first
  if (exerciseDatabase[name]) {
    return exerciseDatabase[name];
  }

  // Try to find a partial match
  const lowerName = name.toLowerCase();
  for (const [key, value] of Object.entries(exerciseDatabase)) {
    if (key.toLowerCase().includes(lowerName) || lowerName.includes(key.toLowerCase())) {
      return value;
    }
  }

  return null;
}
